# Generated by Django 5.0.1 on 2024-01-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_alter_orders_paymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='paymentstatus',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
